text:
  name: "SuperCraftBros"
  prefix: "&e[&6{NAME}&e] "
  primary-color: "6"
  secondary-color: "e"
  error-color: "c"
size:
  min: 2
  max: 4
arena:
  block-break: false
  item-manage: false
  hunger: false
  fire-block-damage: false
  explosion-block-damage: false
modes:
  game-mode: "ADVENTURE"
  exit-mode: "SURVIVAL"
time:
  game-time: 480
  countdown-time: 60
eco:
  winning-eco: 1000
other:
  join-teleport: true
scb:
  lives: 3