name: SuperCraftBros
authors: [Double0negative, MCSG, NextInfinity]
version: @scbversion@
main: net.nextinfinity.supercraftbros.SuperCraftBros
depend: [FastAsyncWorldEdit, ItemNBTAPI]
softdepend: [Vault]
commands:
  quit:
    description: Makes you quit the game
  leave:
    description: Makes you quit the game
  start:
    description: Starts the game
  join:
    description: Makes you join the game
  core:
    description: Core command for managing games and arenas