name: SuperCraftBros
authors: [NextInfinity, Double0negative, MCSG]
version: @scbversion@
api-version: 1.13
main: net.nextinfinity.supercraftbros.SuperCraftBros
depend: [FastAsyncWorldEdit, ItemNBTAPI]
softdepend: [Vault]
commands:
  scb:
    description: SCB command