name: SuperCraftBros
authors: [NextInfinity, Double0negative, MCSG]
version: @scbversion@
api-version: 1.13
main: net.nextinfinity.supercraftbros.SuperCraftBros
depend: [FastAsyncWorldEdit, ItemNBTAPI]
softdepend: [Vault]
commands:
  quit:
    description: Makes you quit the game
  leave:
    description: Makes you quit the game
  start:
    description: Starts the game
  join:
    description: Makes you join the game
  infinitycore:
    description: Core command for managing games and arenas
  scb:
    description: Core command for managing games and arenas